title: Slides for 2017 talks - Bérénice Batut
email: berenice.batut@gmail.com
repository: bebatut-slides/2017
twitter: bebatut
linkedin: berenicebatut
gitter: bebatut
orcid: 0000-0001-9852-1987
scholar: 9sCBSXkAAAAJ
